package rain

import (
	"testing"

	"github.com/hyperlocalise/rain-orm/pkg/schema"
)

func TestCreateTableSQLIdentityPostgres(t *testing.T) {
	type IdentityTable struct {
		schema.TableModel
		ID   *schema.Column[int64]
		Name *schema.Column[string]
	}

	dbPg := MustOpenDialect("postgres")

	t.Run("GeneratedAlways", func(t *testing.T) {
		tbl := schema.Define("test", func(table *IdentityTable) {
			table.ID = table.BigInt("id").GeneratedAlwaysAsIdentity().PrimaryKey()
			table.Name = table.Text("name").NotNull()
		})
		got, err := dbPg.CreateTableSQL(tbl)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := "CREATE TABLE \"test\" (\n\t\"id\" BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,\n\t\"name\" TEXT NOT NULL\n)"
		if got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})

	t.Run("GeneratedByDefault", func(t *testing.T) {
		tbl := schema.Define("test", func(table *IdentityTable) {
			table.ID = table.BigInt("id").GeneratedByDefaultAsIdentity().PrimaryKey()
			table.Name = table.Text("name").NotNull()
		})
		got, err := dbPg.CreateTableSQL(tbl)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		want := "CREATE TABLE \"test\" (\n\t\"id\" BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n\t\"name\" TEXT NOT NULL\n)"
		if got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})

	t.Run("IdentityWithSerialDowngrade", func(t *testing.T) {
		tbl := schema.Define("test", func(table *IdentityTable) {
			table.ID = table.BigSerial("id").GeneratedAlwaysAsIdentity().PrimaryKey()
		})
		got, err := dbPg.CreateTableSQL(tbl)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// BIGSERIAL should be downgraded to BIGINT
		want := "CREATE TABLE \"test\" (\n\t\"id\" BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY\n)"
		if got != want {
			t.Errorf("got %q, want %q", got, want)
		}
	})

	t.Run("InvalidDialect", func(t *testing.T) {
		dbSqlite := MustOpenDialect("sqlite")
		tbl := schema.Define("test", func(table *IdentityTable) {
			table.ID = table.BigInt("id").GeneratedAlwaysAsIdentity().PrimaryKey()
		})
		_, err := dbSqlite.CreateTableSQL(tbl)
		if err == nil {
			t.Fatal("expected error for identity on sqlite, got nil")
		}
	})

	t.Run("ConflictWithDefault", func(t *testing.T) {
		tbl := schema.Define("test", func(table *IdentityTable) {
			table.ID = table.BigInt("id").GeneratedAlwaysAsIdentity().Default(1)
		})
		_, err := dbPg.CreateTableSQL(tbl)
		if err == nil {
			t.Fatal("expected error for identity with default, got nil")
		}
	})

	t.Run("ConflictWithGenerated", func(t *testing.T) {
		tbl := schema.Define("test", func(table *IdentityTable) {
			table.ID = table.BigInt("id").GeneratedAlwaysAsIdentity().GeneratedAlwaysAs(schema.Raw("1"), true)
		})
		_, err := dbPg.CreateTableSQL(tbl)
		if err == nil {
			t.Fatal("expected error for identity with generated, got nil")
		}
	})
}
